backend:
  name: github
  repo: storj/Tardigrade.io
  branch: master
  base_url: https://tardigrade.io
  auth_endpoint: /oauth/auth

media_folder: "static/img/"
public_folder: "/img"
publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "pages"
    folder: "content/pages/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}